# Generated by Django 5.0.7 on 2024-07-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_alter_section_owner"),
    ]

    operations = []
