# Generated by Django 5.0.7 on 2024-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0005_remove_section_owner_section_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="testing",
            name="correct_answers",
            field=models.IntegerField(default=0, verbose_name="Правильные ответы"),
        ),
    ]
