# Generated by Django 5.0.7 on 2024-07-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0007_alter_answer_question_alter_question_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materials",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="education.section",
                verbose_name="Раздел обучения",
            ),
        ),
    ]
