# Generated by Django 5.0.7 on 2024-07-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0008_alter_materials_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTestProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_complete", models.BooleanField(default=False, verbose_name="Завершено")),
                (
                    "correct_answers_count",
                    models.IntegerField(default=0, verbose_name="Количество правильных ответов"),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="education.question",
                        verbose_name="Текущий вопрос",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="education.testing", verbose_name="Тест"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя",
                "verbose_name_plural": "Прогрессы пользователей",
                "unique_together": {("user", "test")},
            },
        ),
    ]
